apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-usop
  labels:
    app: {{ .Release.Name }}-usop
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-usop
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-usop
    spec:
      containers:
        - name: usop
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: PYTHONUNBUFFERED
              value: "1"
          volumeMounts:
            - name: app-volume
              mountPath: /app
      volumes:
        - name: app-volume
          emptyDir: {}