# Generated by Django 5.0.7 on 2024-11-18 21:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_org_users_org_extid_b761d6_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='extid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Automatically genered unique id for external identification', unique=True, verbose_name='ExtID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='extid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Automatically genered unique id for external identification', unique=True, verbose_name='ExtID'),
        ),
    ]
