# Generated by Django 5.0.7 on 2024-12-18 18:50

import django.db.models.deletion
import usop.apps.users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_org_extid_alter_user_extid'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='orgs/logos'),
        ),
        migrations.AddField(
            model_name='org',
            name='namespace',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Automatically genered unique id for namespace',  null=True, verbose_name='Namespace ID'),
        ),
        migrations.AlterField(
            model_name='org',
            name='extid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Automatically generated unique id for external identification', unique=True, verbose_name='ExtID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='extid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Automatically generated unique id for external identification', unique=True, verbose_name='ExtID'),
        ),
        migrations.CreateModel(
            name='MembershipInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('permission', models.CharField(choices=[(usop.apps.users.models.PermissionType['READ'], 'read'), (usop.apps.users.models.PermissionType['WRITE'], 'write'), (usop.apps.users.models.PermissionType['DELETE'], 'delete'), (usop.apps.users.models.PermissionType['ADMIN'], 'admin')], max_length=10)),
                ('extid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Automatically generated unique id for external identification', unique=True, verbose_name='ExtID')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.org')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['extid'], name='users_membe_extid_ffc220_idx')],
                'unique_together': {('user', 'org')},
            },
        ),
    ]
