# Generated by Django 5.0.7 on 2024-12-18 18:51
# Added to generate namespace field in org model

from django.db import migrations

import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("users", "org")
    for row in MyModel.objects.all():
        row.namespace = uuid.uuid4()
        row.save(update_fields=["namespace"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_org_logo_org_namespace_alter_org_extid_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
