# Generated by Django 5.0.7 on 2024-12-18 18:51

from django.db import migrations, models

import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20241218_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='namespace',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Automatically genered unique id for namespace', unique=True, verbose_name='Namespace ID'),
        ),
    ]
